= Repapering for Mac workstation

There are so many helpfully softwares for different platform. Pls just install and enjoy. every one I deeply used.

== terminal
1. iTerm2:

    `brew cask install iterm2`
** shell_integration

  ```
  curl -L https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | bash                                                                             ✔  11410  11:12:04
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                  Dload  Upload   Total   Spent    Left  Speed
  100  4347  100  4347    0     0   4354      0 --:--:-- --:--:-- --:--:--  4355
  Downloading script from https://iterm2.com/shell_integration/zsh and saving it to /Users/yimin/.iterm2_shell_integration.zsh...
  Checking if /Users/yimin/.zshrc contains iterm2_shell_integration...
  Downloading imgcat...
  Downloading imgls...
  Downloading it2attention...
  Downloading it2check...
  Downloading it2copy...
  Downloading it2dl...
  Downloading it2getvar...
  Downloading it2setcolor...
  Downloading it2setkeylabel...
  Downloading it2ul...
  Downloading it2universion...
  Adding aliases...
  Done.
  --------------------------------------------------------------------------------

  The next time you log in, shell integration will be enabled.

  You will also have these commands:
  imgcat filename
    Displays the image inline.
  imgls
    Shows a directory listing with image thumbnails
  it2attention start|stop|fireworks
    Gets your attention
  it2check
    Checks if the terminal is iTerm2
  it2copy [filename]
    Copies to the pasteboard
  it2dl filename
    Downloads the specified file, saving it in your Downloads folder.
  it2setcolor ...
    Changes individual color settings or loads a color preset
  it2setkeylabel ...
    Changes Touch Bar function key labels
  it2ul
    Uploads a file
  it2universion
    Sets the current unicode version
  ```

2. ohMyZsh:

    `sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"`

3. Syntax highlighting: `brew install zsh-syntax-highlighting`
4. zsh-autosuggestions: `brew install zsh-autosuggestions`
5. https://github.com/zsh-users[zsh-users] - Zsh community projects
6. Theme:
** https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config[powerlevel9k]
** https://draculatheme.com/[draculatheme]
7. https://github.com/powerline/fonts[fonts] - Patched fonts for Powerline users.
8. https://github.com/jakubroztocil/httpie[httpie] image:https://img.shields.io/github/stars/jakubroztocil/httpie.svg?style=for-the-badge&colorB=RED&label=STARTS[stars]   +
Modern command line HTTP client – user-friendly curl alternative with intuitive UI, JSON support, syntax highlighting, wget-like downloads, extensions, etc. https://twitter.com/clihttp https://httpie.org
9. https://github.com/eliangcs/http-prompt/[http-prompt] image:https://img.shields.io/github/stars/eliangcs/http-prompt.svg?style=for-the-badge&colorB=GREEN&label=STARTS[stars] +
HTTP Prompt is an interactive command-line HTTP client featuring autocomplete and syntax highlighting.
10. https://github.com/emre/storm[storm] image:https://img.shields.io/github/stars/emre/storm.svg?style=for-the-badge&colorB=YELLOW&label=STARTS[stars]   +
Manage your SSH like a boss.
11. https://github.com/sharkdp/fd[sharkdp/fd] image:https://img.shields.io/github/stars/sharkdp/fd.svg?style=for-the-badge&colorB=BLUE&label=STARTS[stars]   +
A simple, fast and user-friendly alternative to 'find'
12. https://github.com/skywind3000/z.lua[skywind3000/z.lua] image:https://img.shields.io/github/stars/skywind3000/z.lua.svg?style=for-the-badge&colorB=BLUE&label=STARTS[stars] + A new cd command that helps you navigate faster by learning your habits

== Benchmarking

== Package Manager
1. https://gofi.sh/index.html[GoFish] -  is a cross-platform systems package manager, bringing the ease of use of Homebrew to Linux and Windows.

== RVM
- https://sdkman.io/[SDKMAN] - The Software Development Kit Manager,is a tool for managing parallel versions of multiple Software Development Kits on most Unix based systems. It provides a convenient Command Line Interface (CLI) and API for installing, switching, removing and listing Candidates. Formerly known as GVM the Groovy enVironment Manager, it was inspired by the very useful https://rvm.io/[RVM] and https://github.com/sstephenson/rbenv[rbenv] tools, used at large by the Ruby community. Get started now!  `$ curl -s "https://get.sdkman.io" | bash`
- https://github.com/creationix/nvm[NVP] -  Node Version Manager - Simple bash script to manage multiple active node.js versions.
- https://github.com/pyenv/pyenv[pyenv/pyenv] - Simple Python version management

== Go

== Java

== Python

- https://www.anaconda.com/download/#macos[Anaconda] - The Most Popular Python Data Science Platform,Conda is a powerful package manager and environment manager that you use with command line commands at the Anaconda Prompt  https://conda.io/docs/user-guide/getting-started.html[Docs]
* https://repo.anaconda.com/archive/Anaconda3-5.2.0-MacOSX-x86_64.pkg[64-Bit Graphical Installer (613 MB)]
* https://repo.anaconda.com/archive/Anaconda3-5.2.0-MacOSX-x86_64.sh[64-Bit Command-Line Installer (523 MB)]

==== Install Information
* `brew install python`
* export PATH="/usr/local/opt/python/libexec/bin:$PATH"

```
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python/libexec/bin

If you need Homebrew's Python 2.7 run
  brew install python@2

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
```


== Mac terminal

1. gofish

    `curl -fsSL https://raw.githubusercontent.com/fishworks/gofish/master/scripts/install.sh | bash; gofish init`



== Develop

* https://github.com/localtunnel/localtunnel[localtunnel] image:https://img.shields.io/github/stars/localtunnel/localtunnel.svg?style=for-the-badge&colorB=BLUE&label=STARTS[stars]   +
Expose yourself to the world



== Desktop

* lolcat
* figlet
* cowsay
* http://byobu.co/[Byobu] - is a GPLv3 open source text-based window manager and terminal multiplexer.
* https://github.com/jingweno/ccat[ccat] -  is the colorizing cat. It works similar to cat but displays content with syntax highlighting.
* https://github.com/chrisallenlane/cheat[cheat] - cheat allows you to create and view interactive cheatsheets on the command-line. It was designed to help remind *nix system administrators of options for commands that they use frequently, but not frequently enough to remember.
* https://github.com/pindexis/marker[pindexis/marker] - is a command palette for the terminal. It lets you bookmark commands (or commands templates) and easily retreive them with the help of a real-time fuzzy matcher.
* https://github.com/tldr-pages/tldr[tldr] - Simplified and community-driven man pages http://tldr-pages.github.io/
* https://asciinema.org/[asciinema] - Record and share your terminal sessions, the right way.


https://github.com/sshconfigio/sshconfigio.github.io#remote-copy

https://github.com/alebcay/awesome-shell
https://www.tecmint.com/20-funny-commands-of-linux-or-linux-is-fun-in-terminal/
https://www.tecmint.com/linux-funny-commands/
https://www.tecmint.com/play-with-word-and-character-counts-in-linux/
https://www.tecmint.com/free-online-linux-learning-guide-for-beginners/
https://www.tecmint.com/play-with-word-and-character-counts-in-linux/

